# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- powershell: 
    .\Convert-NSGCsvToJson.ps1
  displayName: 'Create JSON rules'
- powershell: | 
    $rules = Get-Content rules.json
    echo "##vso[task.setvariable variable=rulesvar]$rules"
  displayName: 'Assign JSON rules to variable'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'MSDN Platforms Subscription'
    subscriptionId: '$(subscriptionId)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourceGroup)'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: 'azuredeploy.json'
    overrideParameters: '-NSGs $(rulesvar)'
    deploymentMode: 'Incremental'
    deploymentName: 'deploy_$(Date:yyyyMMdd)'


