# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2
      # Login to Azure using secret
      - name: Azure Login
        uses: Azure/login@v1
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      # Read Security Rules from JSON file
      - name: Read NSG JSON rules
        id: output
        run: |
          $file_text = Get-Content "rules.json"
          echo "::set-output name=new_value::$file_text"
          
      # Runs a single command using the runners shell
      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1
        with:
          # Provide the scope of the deployment. Valid values are: 'resourcegroup', 'managementgroup', 'subscription'
          scope: resourcegroup
          # Override the Subscription Id set by Azure Login.
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          # Provide the name of a resource group, only required for resource Group deployments.
          resourceGroupName: testNSG
          # Specify the path or URL to the Azure Resource Manager template.
          template: ./azuredeploy.json
          # Supply deployment parameter values.
          parameters: NSGs=${{ steps.output.outputs.new_value }}
